### ISSUE TITLE
[Roadmap] First Release of AmsDatePicker

### ISSUE THREAD

**Issue by lilingxi01** [lilingxi01/ams-date-picker#2]
# Description

I have already migrated the DatePicker component from its [original repository](https://github.com/mbucc/320-S22-Track2) (by Indigo Development) to here following the open source rule. At the same time, I kept all old contributions from Git, so our original contributor, Yan, can still be an honor contributor of this project.

I am really glad to separate this out and make it reusable. But before releasing it formally, we need to make some changes. Because the original BPDatePicker is not headless and is using MUI as its root input component and its floating date picker panel, we will remove them and all unnecessary dependencies (e.g. MUI), and make it headless, so you can style it with your needs.

This issue is a tracking issue of the first release. We will finish everything on here and then release. I will be very happy if you would like to join this project and contribute to it.

# Rough Roadmap

- [x] Add a README.
- [x] Add ESLint and Lint-checking GitHub Actions.
- [ ] Remove MUI dependencies and replace it using raw HTML elements (or simple library).
- [ ] Separate the component into sections in order to make it headless.
- [ ] (TBD) Also create a headful version of AmsDatePicker.
- [ ] Build a documentation site describing the features and module usage.
- [ ] Add a release branch and auto-release GitHub Actions.

# Related Issues

TBA.

**Comment by lilingxi01** [comment]
@all-contributors please add @limbo-yan for code as she contributed to the algorithm of core processor.
