### ISSUE TITLE
✨ TypeScript Rewrite

### ISSUE THREAD

**Issue by lilingxi01** [lilingxi01/ams-date-picker#27]
# Overview

To make Ams Date Picker type-safe, we may need to rewrite the entire component with TypeScript. This is still a TBD event as we might not choose to do so in a sooner future.

# Tasks

* [x] Finish project configuration.
* [x] Rewrite main algorithms in TypeScript.
* [x] Rewrite main components in TypeScript.
